### ISSUE TITLE
Trigger completion not work as expected when TextDocumentSyncKind is Incremental

### ISSUE THREAD

**Issue by chemzqm** [natebosch/dart_language_server#50]
Trigger completion would sometimes always give global completion items when TextDocumentSyncKind is Incremental.

I use dart code from: https://github.com/flutter/flutter/blob/master/dev/tools/gen_localizations.dart
[dart.log](https://github.com/natebosch/dart_language_server/files/2265690/dart.log)
The log can be checked out with https://microsoft.github.io/language-server-protocol/inspector/

**Comment by natebosch** [comment]
> The log can be checked out with

Can you upload the log?

Incremental sync has been working fine for me with https://github.com/natebosch/vim-lsc as the client. I did have some sync bugs a while back but solved them around here: https://github.com/natebosch/dart_language_server/commit/3643bf6d8956c7215cbed52718f5f8263ab7c2f5

What version of the server are you using? What Dart SDK version?

**Comment by chemzqm** [comment]
The log is uploaded, click `dart.log` to download.
The version is `0.1.12+2`
```
  dart_language_server:
    dependency: "direct main"
    description:
      name: dart_language_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.12+2"
```
